apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: myapp=docker.io/jieun890323/fastapi-app
    argocd-image-updater.argoproj.io/myapp.update-strategy: semver
spec:
  project: default
  source:
    repoURL: https://github.com/studiojessy/new-pro.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: my-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true